export const weatherData = {
  city: "Atlanta",
  country: "US",
  current: {
    temperature: 78,
    feelsLike: 81,
    condition: "Partly Cloudy",
    humidity: 58,
    windSpeed: 1000,
    // N, S, E, W, NNE, NNW, SSE, SSW
    windDirection: "NNW",
    windDegrees: 315,
    pressure: 29,
    visibility: 6,
    uvIndex: 11,
    dewPoint: 30,
    airQuality: 150,
    icon: "🌤️",
    sunriseTime: "7:03 am",
    sunsetTime: "8:15 pm",
    moonriseTime: "4:56 pm",
    moonsetTime: "2:27 am",
    moonPhase: "Waning Crescent",
  },

  hourly: [
    { time: "12 PM", temp: 78, humidity: 62, precipitation: 5 },
    { time: "1 PM", temp: 80, humidity: 60, precipitation: 5 },
    { time: "2 PM", temp: 82, humidity: 58, precipitation: 10 },
    { time: "3 PM", temp: 84, humidity: 55, precipitation: 15 },
    { time: "4 PM", temp: 85, humidity: 54, precipitation: 20 },
    { time: "5 PM", temp: 84, humidity: 56, precipitation: 15 },
    { time: "6 PM", temp: 82, humidity: 58, precipitation: 10 },
    { time: "7 PM", temp: 80, humidity: 60, precipitation: 5 },
    { time: "8 PM", temp: 80, humidity: 60, precipitation: 5 },
    { time: "9 PM", temp: 79, humidity: 60, precipitation: 5 },
    { time: "10 PM", temp: 76, humidity: 60, precipitation: 5 },
    { time: "11 PM", temp: 76, humidity: 60, precipitation: 5 },
    { time: "12 AM", temp: 74, humidity: 60, precipitation: 5 },
    { time: "1 AM", temp: 74, humidity: 60, precipitation: 5 },
    { time: "2 AM", temp: 74, humidity: 60, precipitation: 5 },
    { time: "3 AM", temp: 72, humidity: 60, precipitation: 5 },
    { time: "4 AM", temp: 74, humidity: 60, precipitation: 5 },
    { time: "5 AM", temp: 74, humidity: 60, precipitation: 5 },
    { time: "6 AM", temp: 76, humidity: 60, precipitation: 5 },
    { time: "7 AM", temp: 77, humidity: 60, precipitation: 5 },
    { time: "8 AM", temp: 78, humidity: 60, precipitation: 5 },
    { time: "9 AM", temp: 80, humidity: 60, precipitation: 5 },
    { time: "10 AM", temp: 81, humidity: 60, precipitation: 5 },
    { time: "11 AM", temp: 81, humidity: 60, precipitation: 5 },
  ],
  daily: [
    {
      day: "Mon",
      high: 86,
      low: 72,
      currentTemp: 80,
      feelsLike: 82,
      condition: "Sunny",
      precipitation: 0,
    },
    {
      day: "Tue",
      high: 84,
      low: 70,
      currentTemp: 76,
      feelsLike: 79,
      condition: "Partly Cloudy",
      precipitation: 10,
    },
    {
      day: "Wed",
      high: 81,
      low: 69,
      currentTemp: 74,
      feelsLike: 70,
      condition: "Rain",
      precipitation: 80,
    },
    {
      day: "Thu",
      high: 79,
      low: 68,
      currentTemp: 75,
      feelsLike: 83,
      condition: "Thunderstorm",
      precipitation: 90,
    },
    {
      day: "Fri",
      high: 83,
      low: 70,
      currentTemp: 77,
      feelsLike: 85,
      condition: "Cloudy",
      precipitation: 30,
    },
    {
      day: "Sat",
      high: 87,
      low: 73,
      currentTemp: 80,
      feelsLike: 87,
      condition: "Sunny",
      precipitation: 0,
    },
    {
      day: "Sun",
      high: 88,
      low: 74,
      currentTemp: 80,
      feelsLike: 74,
      condition: "Sunny",
      precipitation: 0,
    },
  ],
};

// const temperatureHistory = [
//   { date: "Jun 1", temp: 76 },
//   { date: "Jun 2", temp: 79 },
//   { date: "Jun 3", temp: 81 },
//   { date: "Jun 4", temp: 84 },
//   { date: "Jun 5", temp: 82 },
//   { date: "Jun 6", temp: 78 },
//   { date: "Jun 7", temp: 80 },
//   { date: "Jun 8", temp: 83 },
//   { date: "Jun 9", temp: 85 },
//   { date: "Jun 10", temp: 87 },
//   { date: "Jun 11", temp: 86 },
//   { date: "Jun 12", temp: 84 },
//   { date: "Jun 13", temp: 82 },
//   { date: "Jun 14", temp: 79 },
// ];

export default weatherData;
